## Data set creation
We are sampling 1000 data points from the test data set and comparing how a human performs vs our best algorithm.

In [68]:
import pandas as pd
import numpy as np

In [69]:
data_path = "../data/raw_data/test.csv"

In [70]:
data = pd.read_csv(data_path)
comments = data['Comment']
labels = data['Labels']

In [71]:
test_data = pd.DataFrame({'Comment': comments[1000:2000]})
test_labels = labels[1000:2000]
test_labels

1000    0
1001    0
1002    0
1003    0
1004    0
1005    0
1006    0
1007    0
1008    0
1009    0
1010    1
1011    0
1012    0
1013    0
1014    0
1015    0
1016    0
1017    0
1018    0
1019    0
1020    0
1021    0
1022    0
1023    0
1024    0
1025    0
1026    0
1027    0
1028    0
1029    0
       ..
1970    0
1971    0
1972    0
1973    0
1974    1
1975    0
1976    0
1977    0
1978    0
1979    0
1980    0
1981    0
1982    0
1983    1
1984    0
1985    0
1986    0
1987    0
1988    0
1989    0
1990    0
1991    0
1992    0
1993    0
1994    0
1995    0
1996    0
1997    0
1998    1
1999    0
Name: Labels, Length: 1000, dtype: int64

In [72]:
test_data.to_csv('test_data.csv')

In [73]:
trial = pd.read_csv('test_data.csv')

In [74]:
labelled_test = pd.read_csv('test_data_labelled')
y_pred_human = labelled_test['Labels'][:1000]
y_pred_human

0      0.0
1      0.0
2      0.0
3      0.0
4      1.0
5      0.0
6      0.0
7      1.0
8      0.0
9      0.0
10     1.0
11     0.0
12     0.0
13     0.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     1.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
      ... 
970    0.0
971    0.0
972    0.0
973    0.0
974    1.0
975    0.0
976    0.0
977    0.0
978    0.0
979    0.0
980    0.0
981    0.0
982    0.0
983    1.0
984    0.0
985    1.0
986    0.0
987    0.0
988    0.0
989    0.0
990    0.0
991    0.0
992    0.0
993    0.0
994    0.0
995    0.0
996    0.0
997    0.0
998    1.0
999    0.0
Name: Labels, Length: 1000, dtype: float64

In [75]:
from sklearn.metrics import confusion_matrix, roc_auc_score
confmat = confusion_matrix(test_labels, y_pred_human)
print(confmat)
roc_auc = roc_auc_score(test_labels, y_pred_human, 'macro')
print("ROC AUC score mean: %f" % (roc_auc))

[[877  37]
 [ 24  62]]
ROC AUC score mean: 0.840224


In [80]:
y_syn = np.zeros(1000)

In [81]:
y_syn

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [82]:
from sklearn.metrics import confusion_matrix, roc_auc_score
confmat = confusion_matrix(test_labels, y_syn)
print(confmat)
roc_auc = roc_auc_score(test_labels, y_syn, 'macro')
print("ROC AUC score mean: %f" % (roc_auc))

[[914   0]
 [ 86   0]]
ROC AUC score mean: 0.500000
